[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  Network = "ephemeral"
  Bootstrapper = false
  BootstrapPeers = []
  MutualPeers = []
  PeerExchange = false
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = 60000000000

[RPC]
  ListenAddr = ""

[Services]
  TrustedHash = "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96"
  TrustedPeer = "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw"
