version: '3'

services:
  light0:
    container_name: light0
    image: "ghcr.io/jbowen93/celestia-node:v0.1.2"
    environment:
      - NODE_TYPE=light
    command: [
            "celestia", "light",
            "--repo.path", "/celestia-light",
            "start",
            "--headers.trusted-peer",
            "/ip4/192.167.10.6/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw",
            "--headers.trusted-hash", 
            "54A8B66D2BEF13850D67C8D474E196BD7485FE5A79989E31B17169371B0A9C96"
             ]
    volumes:
       - ${PWD}/celestia-node/light/light0/nodekey0:/celestia-light/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.10.10

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
