version: '3'

services:
  evmos0:
    container_name: evmos0
    image: "ghcr.io/jbowen93/evmos:latest2"
    command: [
            "evmosd", "start",
            "--home", "/root",
            "--optimint.aggregator", "true",
            "--optimint.block_time", "30s",
            "--optimint.namespace_id", "0000DEADBEEF0000",
            "--optimint.da_layer", "grpc",
            "--optimint.da_config", '{"host":"192.167.10.14", "port":4200}',
            "--rpc.laddr", "tcp://0.0.0.0:26657",
             ]
    networks:
      localnet:
        ipv4_address: 192.167.10.15

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
